---
sidebar: sidebar 
permalink: express/express-direct-attach-design_technology_requirements.html 
keywords: requirements, hardware, software, A220, HA, VIC, B200 m5, fabric interconnect, VMware, vCenter, Server, Appliance, ESXi, hypervisor 
summary: FlexPod 快速系统需要硬件和软件组件的组合。FlexPod Express 还介绍了以两个单位向系统添加虚拟机管理程序节点所需的硬件组件。 
---
= 技术要求
:allow-uri-read: 


FlexPod 快速系统需要硬件和软件组件的组合。FlexPod Express 还介绍了以两个单位向系统添加虚拟机管理程序节点所需的硬件组件。



== 硬件要求

无论选择何种虚拟机管理程序，所有 FlexPod 快速配置都使用相同的硬件。因此，即使业务需求发生变化，任何虚拟机管理程序都可以在同一个 FlexPod Express 硬件上运行。

下表列出了所有 FlexPod 快速配置所需的硬件组件。

[cols="50,50"]
|===
| 硬件 | 数量 


| AFF A220 HA 对 | 1. 


| Cisco UCS B200 M5 服务器 | 2. 


| Cisco Nexus 31108PCV 交换机 | 2. 


| 适用于 B200 M5 服务器的 Cisco UCS 虚拟接口卡（ VIC ） 1440 | 2. 


| 具有两个集成 UCS-FI-M-6324 互联阵列的 Cisco UCS Mini | 1. 
|===


== 软件要求

下表列出了实施 FlexPod 快速解决方案架构所需的软件组件。

[cols="33,33,33"]
|===
| 软件 | version | 详细信息 


| Cisco UCS Manager | 4.0 （ 1b ） | 适用于 Cisco UCS 互联阵列 FI-6324UP 


| Cisco 刀片式服务器软件 | 4.0 （ 1b ） | 适用于 Cisco UCS B200 M5 服务器 


| Cisco nenic 驱动程序 | 1.0.25.0 | 适用于 Cisco VIC 1440 接口卡 


| Cisco NX-OS | 7.0 （ 3 ） I6 （ 1 ） | 适用于 Cisco Nexus 31108PCV 交换机 


| NetApp ONTAP | 9.5 | 适用于 AFF A220 控制器 
|===
下表列出了在 FlexPod Express 上实施所有 VMware vSphere 所需的软件。

[cols="50,50"]
|===
| 软件 | version 


| VMware vCenter Server 设备 | 6.7U1 


| VMware vSphere ESXi 虚拟机管理程序 | 6.7U1 
|===
link:express-direct-attach-design_design_choices.html["接下来：设计选择。"]
