---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: 本文档详细介绍了如何配置完全冗余，高可用性的 FlexPod Express 系统。为了反映这种冗余，在每个步骤中配置的组件称为组件 A 或组件 B 
---
= 概述
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


本文档详细介绍了如何配置完全冗余，高可用性的 FlexPod Express 系统。为了反映这种冗余，在每个步骤中配置的组件称为组件 A 或组件 B例如，控制器 A 和控制器 B 可识别本文档中配置的两个 NetApp 存储控制器。交换机 A 和交换机 B 可识别一对 Cisco Nexus 交换机。

此外，本文档还介绍配置多个 Cisco UCS 主机的步骤，这些主机按顺序标识为服务器 A ，服务器 B 等。

要指示您应在步骤中包含与您的环境相关的信息，请在命令结构中显示 ` \<<text>>` 。请参见以下 `vlan create` 命令示例：

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
通过本文档，您可以完全配置 FlexPod 快速环境。在此过程中，您需要通过多个步骤插入客户专用的命名约定， IP 地址和虚拟局域网（ VLAN ）方案。下表介绍了部署所需的 VLAN ，如本指南所述。此表可根据特定站点变量填写，并用于实施文档配置步骤。


NOTE: 如果使用单独的带内和带外管理 VLAN ，则必须在它们之间创建第 3 层路由。在此验证中，使用了一个通用管理 VLAN 。

|===
| VLAN name | VLAN 用途 | VLAN ID |  


| 管理 VLAN | 用于管理接口的 VLAN | 3437 | vSwitch0 


| NFS VLAN | 用于 NFS 流量的 VLAN | 3438 | vSwitch0 


| VMware vMotion VLAN | 为将虚拟机（ VM ）从一台物理主机移动到另一台物理主机而指定的 VLAN | 3441 | vSwitch0 


| VM 流量 VLAN | 用于 VM 应用程序流量的 VLAN | 3442 | vSwitch0 


| iSCSI-A-VLAN | 网络结构 A 上用于 iSCSI 流量的 VLAN | 3439 | iScsiBootvSwitch 


| iSCSI-B-VLAN | 网络结构 B 上用于 iSCSI 流量的 VLAN | 3440 | iScsiBootvSwitch 


| 原生 VLAN | 将未标记的帧分配到的 VLAN | 2. |  
|===
在整个 FlexPod Express 配置过程中都需要 VLAN 编号。这些 VLAN 称为 ` \<<var_xxxx_vlan>>` ，其中 `xxxx` 是 VLAN 的用途（例如 iSCSI-A ）。

在此验证中创建了两个 vSwitch 。

下表列出了解决方案 vSwitch 。

|===
| vSwitch 名称 | 活动适配器 | 端口 | MTU | 负载平衡 


| vSwitch0 | vmnic2 ， vmnic4 | 默认值（ 120 ） | 9000 | 基于 IP 哈希的路由 


| iScsiBootvSwitch | vmnic3 ， vmnic5 | 默认值（ 120 ） | 9000 | 基于源虚拟端口 ID 的路由。 
|===

NOTE: 负载平衡的 IP 哈希方法需要使用具有静态（模式开启）端口通道的 SRC/DST-IP EtherChannel 为底层物理交换机进行正确配置。如果由于交换机配置不当而导致连接间歇性中断，请暂时关闭 Cisco 交换机上两个关联上行链路端口之一，以便在对端口通道设置进行故障排除时恢复与 ESXi 管理 vmkernel 端口的通信。

下表列出了已创建的 VMware VM 。

|===
| VM 问题描述 | 主机名 


| VMware vCenter Server | FlexPod-VCSA 


| Virtual Storage Console | FlexPod-VSC 
|===