---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, cisco, ucs, fabric, interconnect, uplink, direct, san 
summary: 下面列出了 FlexPod 配置的连接要求。 
---
= 连接要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FlexPod 配置具有以下连接要求：

* 所有组件都需要单独的 1Gb 以太网带外管理网络。
* NetApp 建议您在整个环境中启用巨型帧支持，但这并不是必需的。
* 独立的 Cisco UCS Fabric Interconnect 设备端口仅建议用于 iSCSI 连接。当 NAS 连接与设备端口一起使用时，某些故障情况下需要额外的 Cisco Nexus 或等效的以太网交换机。
* 不能在核心 FlexPod 组件之间直列放置任何其他设备。


上行链路连接：

* NetApp 存储控制器上的端口必须连接到 Cisco Nexus 9000 系列交换机。
* 需要从 Cisco Nexus 9000 系列交换机到 NetApp 存储控制器的 vPC。
* 从 Cisco Nexus 9000 系列交换机到交换矩阵互联需要 vPC。
* 一个 vPC 至少需要两个连接。可以根据应用程序负载和性能要求增加 vPC 中的连接数。


直接连接：

* NetApp 存储控制器端口（直接连接到交换矩阵互联，如 X-Series Direct）可以分组以启用端口通道。此配置不支持 vPC。
* 建议将 FCoE 端口通道用于端到端 FCoE 设计。


SAN 启动：

* FlexPod 解决方案是围绕使用 iSCSI ， FC 或 FCoE 协议的 SAN 启动架构设计的。使用从 SAN 启动技术可以为数据中心基础架构提供最灵活的配置，并可在每个基础架构组件中提供丰富的功能。尽管从 SAN 启动是最高效的配置，但从本地服务器存储启动是一种有效且受支持的配置。
* 不支持通过FC-NVMe进行SAN引导。


有关每个拓扑特定的连接要求，请参见 link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter 拓扑"^] 部分。
