---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: FlexPod 数据中心配置具有最低硬件要求，包括但不限于交换机，互联阵列，服务器和 NetApp 存储控制器。 
---
= 最低硬件要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FlexPod 数据中心配置具有最低硬件要求，包括但不限于交换机，互联阵列，服务器和 NetApp 存储控制器。

FlexPod 配置具有以下最低硬件要求：

* 两个采用冗余配置的 Cisco Nexus 交换机。此配置可以由前面提到的 Cisco Nexus 9000 系列的两台冗余交换机组成。这两台交换机应为同一型号，并应配置为相同的运行模式。



NOTE: 如果要部署 ACI 架构，则必须遵守以下附加要求： * 在叶脊拓扑中部署 Cisco Nexus 9000 系列交换机。* 使用三个 Cisco Application Policy Infrastructure Controller (APIC)。

* 两个冗余配置的 Cisco UCS 6400、6500 或 6600 系列 Fabric Interconnect（如果使用 UCS C-Series 机架式服务器或 X-Series 模块化系统）。
* 两个具有 FI 连接的 Cisco UCS C-Series 机架式服务器（采用 Intersight Managed Mode 配置 (IMM)）、Cisco UCS X-Series Direct（采用 Cisco IMM）或 Cisco UCS X-Series Modular（采用 Cisco IMM）。



NOTE: 如果使用的是没有 FI 连接的 UCS 机架服务器，则可以使用 CIMC 或 Intersight 独立模式进行管理 (ISM)。

* 在高可用性 (HA) 对配置中，两个 NetApp AFF、NetApp ASA 或 NetApp FAS 控制器部署为双节点集群。如果使用 NetApp AFX，则至少需要四个 NetApp AFX 控制器，并且必须部署为具有 2 个 HA 对以及一对集群互连交换机的四节点集群。
* 对于没有内置磁盘架的存储控制器，至少需要一个 NetApp 磁盘架。

