---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp 存储控制器为 FlexPod Express 架构中的启动和应用数据存储提供了存储基础。本节列出了 FlexPod Express 架构中不同的 NetApp 存储选项。 
---
= NetApp 组件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp 存储控制器在 FlexPod 快速架构中为启动和应用程序数据存储提供了存储基础。本节列出了 FlexPod 快速架构中的不同 NetApp 选项。



== NetApp 存储控制器选项

在 FlexPod Express 架构中需要冗余 AFF、ASA 或 FAS 系列控制器。控制器运行 ONTAP 软件。订购存储控制器时，可以在控制器上预加载首选软件版本。对于 ONTAP，集群可以部署一对集群互连交换机，也可以采用无交换机集群配置进行部署。


NOTE: 只有双节点配置才支持无交换机集群配置。具有 4 个以上节点的配置需要集群互连交换机，而双节点配置则可选。

根据所选的存储平台，提供不同的选项和配置。有关这些附加组件的详细信息，请咨询您的销售代表。

下表中列出的控制器系列适合在 FlexPod 解决方案中使用，因为它们与 Cisco Nexus 交换机的连接是无缝的。有关每个控制器型号的具体兼容性详细信息，请参阅 http://hwu.netapp.com/["NetApp Hardware Universe"^]。

|===
| NetApp 入门级存储系列，适用于 FlexPod Express | 型号 | 技术规格 


.2+| AFF A-Series | A20 .3+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF 文档"] 


| A30 


| AFF C 系列 | C30 


.2+| ASA A 系列 | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA 文档"] 


| A30 


| ASA C 系列 | C30 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 文档"] 


| FAS 2820 
|===


== NetApp 磁盘架和磁盘

存储控制器至少需要一个 NetApp 磁盘架。

选定的 NetApp 磁盘架类型决定了该磁盘架中可用的驱动器类型。


NOTE: 有关所有磁盘架和磁盘部件号，请咨询您的销售代表。

下表列出了 NetApp 磁盘架选项（适用于 FlexPod Express），以及指向其技术规格的链接。

要获取磁盘架支持的驱动器列表，请转到 link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe"^]，在 *产品 > 存储 > 磁盘架* 下选择 *ONTAP（AFF、ASA、FAS）*，选择您正在使用的 ONTAP 版本，然后选择磁盘架类型（例如：*DS212C*），并单击 *Show Results*。单击 *支持的驱动器* 可查看特定 ONTAP 版本和磁盘架所支持的驱动器。

|===
| 磁盘架 | 技术规格 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["磁盘架和存储介质"] 


| DS224C 


| DS460C 


| NS224 


| NS224 搭配 NSM100B 
|===


== NetApp 软件许可选项

下表列出了 NetApp 软件许可选项。

|===
| NetApp 软件许可 | 技术规格 


| 适用于 AFF 和 FAS 的 ONTAP One .2+| 有关许可的详细信息，请咨询 NetApp 销售团队。 


| ONTAP One for SAN for ASA 
|===
有关 NetApp 软件许可的详细信息，请参见此链接： https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp 软件许可"^]。



== NetApp 支持许可选项

SupportEdge Premium 许可证是必需的，这些许可证的部件号因 FlexPod 快速设计中选择的选项而异。

下表列出了 NetApp AFF、ASA 和 FAS 存储系统的 NetApp 支持许可选项。

|===
| NetApp 支持许可 | 技术规格 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===