---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-installation-and-configuration.html 
keywords: cloud volumes ontap, flexpod, ontap netapp console, installation, configuration 
summary: 本节介绍如何安装和配置Cloud Volumes ONTAP、 FlexPod、 ONTAP存储和NetApp Console。 
---
= 安装和配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-solution-components.html["先前版本：解决方案 组件。"]



== NetApp Cloud Volumes ONTAP 部署

完成以下步骤以配置Cloud Volumes ONTAP 实例：

. 准备公共云服务提供商环境。
+
您必须捕获解决方案 配置的公共云服务提供商的环境详细信息。例如、对于Amazon Web Services (AWS)环境准备、您需要AWS访问密钥、AWS机密密钥以及区域、VPC、子网等其他网络详细信息。

. 配置VPC端点网关。
+
要启用VPC与AWS S3服务之间的连接、需要使用VPC端点网关。此操作用于在CVO上启用备份、CVO是网关类型的端点。

. 访问NetApp Console。
+
要访问控制台和其他云服务，您需要注册。 https://cloudmanager.netapp.com/["NetApp Console"^] 。有关在控制台帐户中设置工作区和用户的信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/index.html["NetApp Console设置和管理"^]。您需要一个具有权限的帐户，才能直接从控制台在您的云提供商处部署控制台代理。要获取所需的权限，请参阅 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions.html["NetApp Console的权限摘要"^]。

. 部署控制台代理。
+
在添加 Cloud Volume ONTAP系统之前，必须先部署控制台代理。如果您尝试在没有安装控制台代理的情况下创建第一个Cloud Volumes ONTAP系统，控制台会提示您。要从控制台在 AWS 中部署控制台代理，请参阅以下内容： https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["AWS 中的控制台代理安装选项"^] 。

. 在AWS中启动Cloud Volumes ONTAP。
+
您可以在单系统配置中或在 AWS 中作为 HA 对启动 Cloud Volumes ONTAP 。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-aws.html["阅读分步说明"^]。

+
有关这些步骤的详细信息、请参见 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["AWS中的Cloud Volumes ONTAP 快速入门指南"^]。

+
在这个解决方案中，我们在 AWS 上部署了一个单节点Cloud Volumes ONTAP系统。





== 内部FlexPod 部署

要了解采用UCS X系列的FlexPod 、VMware和NetApp ONTAP 的设计详细信息、请参见 https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["采用Cisco UCS X系列的FlexPod 数据中心"^] 设计指南。本文档提供了在FlexPod 数据中心基础架构中整合Cisco Intersight-managed UCS X系列平台的设计指导。

有关部署内部FlexPod 实例的信息、请参见 https://netapp-https:/www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.htmlmy.sharepoint.com/personal/dorianh_netapp_com/Documents/Projects/Github%20Conversions/FlexPod/TR-4960/TR-4960%20FlexPod%20hybrid%20cloud%20with%20CVO%20for%20Epic%20latest-Feb14.docx["本部署指南"^]。

本文档提供了在FlexPod 数据中心基础架构中整合Cisco Intersight-managed UCS X系列平台的部署指导。本文档介绍了成功部署的配置和最佳实践。

FlexPod 既可以部署在UCS托管模式下、也可以部署在Cisco Intersight托管模式(IMM)下。如果要在UCS托管模式下部署FlexPod 、请参见此内容 https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["设计指南"^] 这是 https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["部署指南"^]。

使用Ansible可以通过基础架构作为代码自动部署FlexPod。下面是用于端到端FlexPod 部署的GitHub存储库的链接：

* 可以看到在UCS托管模式、NetApp ONTAP 和VMware vSphere下使用Cisco UCS的FlexPod 的可识别配置 https://github.com/ucs-compute-solutions/FlexPod-UCSM-M6["此处"^]。
* 可以看到在IMM、NetApp ONTAP 和VMware vSphere中使用Cisco UCS的FlexPod 的可识别配置 https://github.com/ucs-compute-solutions/FlexPod-IMM-4.2.2["此处"^]。




== 内部ONTAP 存储配置

本节介绍特定于此解决方案 的一些重要ONTAP 配置步骤。

. 在运行iSCSI服务的情况下配置SVM。
+
....
1. vserver create -vserver Healthcare_SVM -rootvolume Healthcare_SVM_root -aggregate aggr1_A400_G0312_01 -rootvolume-security-style unix
2. vserver add-protocols -vserver Healthcare_SVM -protocols iscsi
3. vserver iscsi create -vserver Healthcare_SVM

   To verify:

   A400-G0312::> vserver iscsi show -vserver Healthcare_SVM
   Vserver: Healthcare_SVM
   Target Name:
   iqn.1992-08.com.netapp:sn.1fbf00f438c111ed866cd039ea91fb56:vs.3
   Target Alias: Healthcare_SVM
   Administrative Status: up
....
+
如果在集群配置期间未安装iSCSI许可证、请确保在创建iSCSI服务之前安装此许可证。

. 创建FlexVol 卷。
+
....
1. volume create -vserver Healthcare_SVM -volume hc_iscsi_vol -aggregate aggr1_A400_G0312_01 -size 500GB -state online -policy default -space guarantee none
....
. 添加用于iSCSI访问的接口。
+
....
1. network interface create -vserver Healthcare_SVM -lif iscsi-lif-01a -service-policy default-data-iscsi -home-node <st-node01> -home-port a0a-<infra-iscsi-a-vlan-id> -address <st-node01-infra-iscsi-a-ip> -netmask <infra-iscsi-a-mask> -status-admin up
2. network interface create -vserver Healthcare_SVM -lif iscsi-lif-01b -service-policy default-data-iscsi -home-node <st-node01> -home-port a0a-<infra-iscsi-b-vlan-id> -address <st-node01-infra-iscsi-b-ip> -netmask <infra-iscsi-b-mask> -status-admin up
3. network interface create -vserver Healthcare_SVM -lif iscsi-lif-02a -service-policy default-data-iscsi -home-node <st-node02> -home-port a0a-<infra-iscsi-a-vlan-id> -address <st-node02-infra-iscsi-a-ip> -netmask <infra-iscsi-a-mask> -status-admin up
4. network interface create -vserver Healthcare_SVM -lif iscsi-lif-02b -service-policy default-data-iscsi -home-node <st-node02> -home-port a0a-<infra-iscsi-b-vlan-id> -address <st-node02-infra-iscsi-b-ip> -netmask <infra-iscsi-b-mask> -status-admin up
....
+
在此解决方案 中、我们创建了四个iSCSI逻辑接口(LIF)、每个节点上两个。

+
在部署了vCenter并向其添加了所有ESXi主机的情况下启动并运行FlexPod 实例后、我们需要部署一个Linux VM、该VM充当连接和访问NetApp ONTAP 存储的服务器。在此解决方案 中、我们已在vCenter中安装CentOS 8实例。

. 创建LUN。
+
....
1. lun create -vserver Healthcare_SVM -path /vol/hc_iscsi_vol/iscsi_lun1 -size 200GB -ostype linux -space-reserve disabled
....
+
对于EHR操作数据库(ODB)、日志和应用程序工作负载、EHR建议将存储作为iSCSI LUN提供给服务器。如果您的AIX和RHEL操作系统版本支持、则NetApp还支持使用FCP和NVMe/FC、从而提高性能。FCP和NVMe/FC可以同时位于同一个网络结构中。

. 创建igroup。
+
....
1. igroup create -vserver Healthcare_SVM -igroup ehr -protocol iscsi -ostype linux -initiator iqn.1994-05.com.redhat:8e91e9769336
....
+
igroup用于允许服务器访问LUN。对于Linux主机、可以在文件中找到服务器IQN `/etc/iscsi/initiatorname.iscsi`。

. 将 LUN 映射到 igroup 。
+
....
1. lun mapping create -vserver Healthcare_SVM -path /vol/hc_iscsi_vol/iscsi_lun1 -igroup ehr -lun-id 0
....




== 将本地FlexPod存储添加到NetApp Console

使用控制台完成以下步骤，将FlexPod存储添加到系统中。

. 从导航菜单中，选择“存储”>“系统”。
. 在“系统”页面上，单击“添加系统”，然后选择“本地部署”。
. 选择*内部部署ONTAP *。单击 * 下一步 * 。
. 在 "ONTAP 集群详细信息 " 页面上，输入管理员用户帐户的集群管理 IP 地址和密码。然后单击*添加*。
. 在详细信息和凭据页面上、输入工作环境的名称和问题描述 、然后单击*执行*。
+
控制台发现ONTAP集群，并将其作为系统添加到“系统”页面。



有关详细信息、请参见页面 https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["发现内部ONTAP 集群"^]。

link:fhc-cvoe-san-configuration.html["下一步：SAN配置。"]
