---
sidebar: sidebar 
permalink: hybrid-cloud/flexpod-rho-cvo-conclusion.html 
keywords: conclusion 
summary: 在此解决方案 中、我们使用NetApp Astra产品组合为在FlexPod 和AWS上运行的容器化应用程序实施了保护计划。NetApp Astra控制中心和Astra Trident以及Cloud Volumes ONTAP 、Red Hat OpenShift和FlexPod 基础架构构成了此解决方案 的核心组件。 
---
= 结论
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-rho-cvo-application-recovery-with-remote-backups.html["先前：使用远程备份恢复应用程序。"]

[role="lead"]
在此解决方案 中、我们使用NetApp Astra产品组合为在FlexPod 和AWS上运行的容器化应用程序实施了保护计划。NetApp Astra控制中心和Astra Trident以及Cloud Volumes ONTAP 、Red Hat OpenShift和FlexPod 基础架构构成了此解决方案 的核心组件。

我们展示了通过捕获快照保护应用程序的能力、并执行完整备份来在云和内部环境中运行的不同K8s集群之间还原应用程序。

此外、我们还演示了如何跨K8s集群克隆应用程序、从而使客户能够将其应用程序迁移到所需位置的所选K8s集群。

FlexPod 不断发展、客户可以利用它来实现应用程序和业务交付流程的现代化。借助此解决方案 、FlexPod 客户可以放心地为云原生应用程序构建BCDr计划、并将公有 云作为一个位置来实施瞬时或全时灾难恢复计划、同时保持较低的解决方案 成本。

使用Astra Control、您可以将整个应用程序及其数据从一个Kubernetes集群移动到另一个集群、无论这些集群位于何处。它还可以帮助您加快云原生应用程序的部署、操作和保护速度。



== 故障排除

有关故障排除指导、请参见 https://docs.netapp.com/us-en/astra-control-center/support/troubleshooting-acc.html["联机文档"^]。



== 从何处查找追加信息

要了解有关本文档中所述信息的更多信息，请查看以下文档和 / 或网站：

* FlexPod 主页
+
https://www.flexpod.com["https://www.flexpod.com"^]

* 适用于FlexPod 的Cisco验证设计和部署指南
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* 使用Ansible为VMware部署基础架构代码FlexPod
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html#AnsibleAutomationWorkflowandSolutionDeployment"^]

* 使用Ansible将基础架构作为Red Hat OpenShift裸机的代码进行FlexPod 部署
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_iac_redhat_openshift.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_iac_redhat_openshift.html"^]

* Cisco UCS 硬件和软件互操作性工具
+
https://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Cisco Intersight数据表
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* NetApp Astra文档
+
https://docs.netapp.com/us-en/astra-control-center/index.html["https://docs.netapp.com/us-en/astra-control-center/index.html"^]

* NetApp Astra 控制中心
+
https://docs.netapp.com/us-en/astra-control-center/index.html["https://docs.netapp.com/us-en/astra-control-center/index.html"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/trident/index.html["https://docs.netapp.com/us-en/trident/index.html"^]

* NetApp Cloud Manager
+
https://docs.netapp.com/us-en/occm/concept_overview.html["https://docs.netapp.com/us-en/occm/concept_overview.html"^]

* NetApp Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/occm/task_getting_started_aws.html["https://docs.netapp.com/us-en/occm/task_getting_started_aws.html"^]

* Red Hat OpenShift
+
https://www.openshift.com/["https://www.openshift.com/"^]

* NetApp 互操作性表工具
+
http://support.netapp.com/matrix/["http://support.netapp.com/matrix/"^]





== 版本历史记录

|===
| version | Date | 文档版本历史记录 


| 版本 1.0 | 2022年7月 | 针对ACC22.04.0的版本。 
|===