---
sidebar: sidebar 
permalink: flexpod-dc/sm-bcs-where-to-find-additional-information-and-version-history.html 
keywords:  
summary:  
---
= 从何处查找追加信息和版本历史记录
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:sm-bcs-conclusion.html["上一篇：结论。"]

[role="lead"]
要了解有关本文档中所述信息的更多信息，请查看以下文档和 / 或网站：



== FlexPod

* FlexPod 主页
+
https://www.flexpod.com["https://www.flexpod.com"^]

* 适用于 FlexPod 的 Cisco 验证设计和部署指南
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* Cisco 服务器—统一计算系统（ Unified Computing System ， UCS ）
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html"^]

* NetApp 产品文档
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* 采用 UCS 托管模式的 FlexPod Datacenter 4.2 （ 1 ）， VMware vSphere 7.0 U2 和 NetApp ONTAP 9.9 设计指南
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html"^]

* 《采用 UCS 托管模式的 FlexPod UCS 4.2 （ 1 ）， VMware vSphere 7.0 U2 和 NetApp ONTAP 9.9 部署指南》
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html"^]

* 采用 Cisco UCS X 系列， VMware 7.0 U2 和 NetApp ONTAP 9.9 的 FlexPod 数据中心设计指南
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]

* 《采用 Cisco UCS X 系列， VMware 7.0 U2 和 NetApp ONTAP 9.9 的 FlexPod 数据中心部署指南》
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html"^]

* 《采用 Cisco UCS Mini 和 NetApp AFF/FAS NVA 的 VMware vSphere 7.0 FlexPod 快速设计指南》
+
https://www.netapp.com/pdf.html?item=/media/22621-nva-1154-DESIGN.pdf[]

* 《适用于采用 Cisco UCS Mini 和 NetApp AFF/FAS NVA 的 VMware vSphere 7.0 的 FlexPod 快速部署指南》
+
https://www.netapp.com/pdf.html?item=/media/21938-nva-1154-DEPLOY.pdf[]

* 采用 VXLAN 多站点前端网络结构的 FlexPod MetroCluster IP
+
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf["https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf"^]

* NAbox
+
https://nabox.org["https://nabox.org"^]

* NetApp 收获
+
https://github.com/NetApp/harvest/releases["https://github.com/NetApp/harvest/releases"^]





== SM — BC

* SM — BC
+
https://docs.netapp.com/us-en/ontap/smbc/index.html["https://docs.netapp.com/us-en/ontap/smbc/index.html"^]

* TR-4878 ：《 SnapMirror 业务连续性（ SM-BC ） ONTAP 9.8 》
+
https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf["https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf"^]

* 如何正确删除 SnapMirror 关系 ONTAP 9
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_correctly_delete_a_SnapMirror_relationship_ONTAP_9["https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_correctly_delete_a_SnapMirror_relationship_ONTAP_9"^]

* SnapMirror 同步灾难恢复基础知识
+
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html["https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html"^]

* 异步 SnapMirror 灾难恢复基础知识
+
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html#data-protection-relationships"^]

* 数据保护和灾难恢复
+
https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html"^]

* 安装或升级 ONTAP 调解器服务
+
https://docs.netapp.com/us-en/ontap/mediator/index.html["https://docs.netapp.com/us-en/ontap/mediator/index.html"^]





== VMware vSphere HA 和 vSphere Metro Storage Cluster

* 创建和使用 vSphere HA 集群
+
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html"^]

* VMware vSphere 城域存储集群（ VMSC ）
+
https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc"^]

* VMware vSphere Metro Storage Cluster 建议的实践
+
https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-recommended-practices["https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-recommended-practices"^]

* 采用 NetApp SnapMirror 业务连续性（ SM-BC ）和 VMware vSphere Metro Storage Cluster （ VMSC ）的 NetApp ONTAP 。（ 83370 ）
+
https://kb.vmware.com/s/article/83370["https://kb.vmware.com/s/article/83370"^]

* 使用 VMware vSphere Metro Storage Cluster 和 ONTAP 保护第 1 层应用程序和数据库
+
https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-tier-1-applications-and-databases-with-VMware-vSphere-Metro-Storage/ba-p/171636["https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-tier-1-applications-and-databases-with-VMware-vSphere-Metro-Storage/ba-p/171636"^]





== Microsoft SQL 和 HammerDB

* Microsoft SQL Server 2019
+
https://www.microsoft.com/en-us/sql-server/sql-server-2019["https://www.microsoft.com/en-us/sql-server/sql-server-2019"^]

* 《在 VMware vSphere 上构建 Microsoft SQL Server 最佳实践指南》
+
https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-best-practices-guide.pdf["https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-best-practices-guide.pdf"^]

* HammerDB 网站
+
https://www.hammerdb.com["https://www.hammerdb.com"^]





== 兼容性表

* Cisco UCS 硬件兼容性列表
+
https://ucshcltool.cloudapps.cisco.com/public/["https://ucshcltool.cloudapps.cisco.com/public/"^]

* NetApp 互操作性表工具
+
https://support.netapp.com/matrix/["https://support.netapp.com/matrix/"^]

* NetApp Hardware Universe
+
https://hwu.netapp.com["https://hwu.netapp.com"^]

* VMware 兼容性指南
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





== 版本历史记录

|===
| version | Date | 文档版本历史记录 


| 版本 1.0 | 2022 年 4 月 | 初始版本。 
|===