---
sidebar: sidebar 
permalink: security/flexpod-fips-additional-flexpod-security-consideration.html 
keywords: security, cisco intersight, fpolicy, data at rest, data in flight, secure multitenancy 
summary: FlexPod 基础架构是一个模块化，融合，可选择虚拟化，可扩展（横向扩展和纵向扩展）以及经济高效的平台。借助 FlexPod 平台，您可以独立横向扩展计算，网络和存储，加快应用程序部署速度。模块化架构支持无中断运行，即使在系统横向扩展和升级活动期间也是如此。 
---
= 其他 FlexPod 安全注意事项
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-solution-benefits-of-flexpod-converged-infrastructure.html["上一篇： FlexPod 融合基础架构的解决方案 优势。"]

FlexPod 基础架构是一个模块化，融合，可选择虚拟化，可扩展（横向扩展和纵向扩展）以及经济高效的平台。借助 FlexPod 平台，您可以独立横向扩展计算，网络和存储，加快应用程序部署速度。模块化架构支持无中断运行，即使在系统横向扩展和升级活动期间也是如此。

HIT 系统的不同组件要求将数据存储在 SMB/CIFS ， NFS ， ext4 和 NTFS 文件系统中。这一要求意味着基础架构必须通过 NFS ， CIFS 和 SAN 协议提供数据访问。一个 NetApp 存储系统可以支持所有这些协议，因此不再需要采用传统的协议专用存储系统。此外，一个 NetApp 存储系统还可以支持多个命中工作负载，例如 EHRs ， PACS 或 VNA ，基因组学， VDI 等。 具有有保障且可配置的性能级别。

在 FlexPod 系统中部署时， Hit 可提供医疗保健行业特有的多项优势。下面列出了这些优势的高级问题描述 ：

* * FlexPod 安全性 * 。安全性是 FlexPod 系统的基础。在过去几年中，勒索软件已成为一种威胁。勒索软件是一种基于密码学的恶意软件，它使用加密技术构建恶意软件。此恶意软件可以使用对称密钥加密和非对称密钥加密来锁定受影响的数据，并要求勒索以提供密钥来对数据进行解密。要了解 FlexPod 解决方案 如何帮助缓解勒索软件等威胁，请参见 https://www.netapp.com/us/media/tr-4802.pdf["TR-4802 ：《从解决方案 到勒索软件》"^]。FlexPod 基础架构组件也是。
* * Cisco Intersight 。 * Cisco Intersight 是一款基于云的创新型管理即服务平台，可为全堆栈 FlexPod 管理和编排提供单一管理平台。Intersight 平台使用符合 FIPS 140-2 安全标准的加密模块。该平台的带外管理架构使其超出了某些标准或审计范围，例如 HIPAA 。网络上任何可识别的个人运行状况信息都不会发送到 Intersight 门户。
* * NetApp FPolicy 技术。 * NetApp FPolicy （名称文件策略的演变）是一个文件访问通知框架，用于通过 NFS 或 SMB/CIFS 协议监控和管理文件访问。这项技术已成为 ONTAP 数据管理软件的一部分已有十多年来的发展，它有助于检测勒索软件。此零信任引擎提供的安全措施超出了访问控制列表（ ACL ）中的权限范围。FPolicy 有两种操作模式：原生 和外部：
+
** 原生 模式同时提供了文件扩展名的黑名单和白名单功能。
** 外部模式与原生 模式具有相同的功能，但它还与在 ONTAP 系统外部运行的 FPolicy 服务器以及安全信息和事件管理（ Security Information and Event Management ，）系统集成。有关如何打击勒索软件的详细信息，请参见 https://blog.netapp.com/fighting-ransomware-tools["《与勒索软件作斗争》：第三部分— ONTAP FPolicy ，另一款功能强大的原生 （也称为免费）工具"^] 博客


* * 空闲数据 * 。ONTAP 9 及更高版本提供了三种符合 FIPS 140-2 标准的空闲数据加密解决方案：
+
** NSE 是一种使用自加密驱动器的硬件解决方案 。
** NVE 是一种软件解决方案，用于对任何驱动器类型上的任何数据卷进行加密，其中每个卷都有一个唯一的密钥。
** NAE 是一种软件解决方案，用于对任何驱动器类型上的任何数据卷进行加密，其中每个聚合都使用唯一的密钥启用数据卷。





NOTE: 从 ONTAP 9.7 开始，如果已安装名为 VE 的 NetApp NVE 许可证包，则默认情况下会启用 NAE 和 NVE 。

* * 数据正在传输 * 。从 ONTAP 9.8 开始，互联网协议安全（ Internet Protocol Security ， IPsec ）为客户端与 ONTAP SVM 之间的所有 IP 流量提供端到端加密支持。所有 IP 流量的 IPsec 数据加密包括 NFS ， iSCSI 和 SMB/CIFS 协议。IPsec 为 iSCSI 流量提供了唯一的传输加密选项。
* * 跨混合多云数据网络结构的端到端数据加密 * 。现在，使用 NSE 或 NVE 等空闲数据加密技术以及集群对等加密（ Cluster peering Encryption ， CPE ）传输数据复制流量的客户可以通过升级到 ONTAP 9.8 或更高版本并使用 IPsec 在混合多云数据网络结构中的客户端和存储之间使用端到端加密。从 ONTAP 9 开始，您可以为集群范围的控制面板接口启用 FIPS 140-2 合规模式。默认情况下，仅 FIPS 140-2 模式处于禁用状态。从 ONTAP 9.6 开始， CPe 为 ONTAP 数据复制功能（例如 NetApp SnapMirror ， NetApp SnapVault 和 NetApp FlexCache 技术）提供 TLS 1.2 AES-256 GCM 加密支持。加密可通过两个集群对等方之间的预共享密钥（ PSk ）进行设置。
* * 安全多租户 * 。支持日益增长的虚拟化服务器和存储共享基础架构需求，从而可以安全地多租户特定于设施的信息，尤其是在托管多个数据库和软件实例时。


link:flexpod-fips-conclusion.html["接下来：总结。"]
