---
sidebar: sidebar 
permalink: security/flexpod-fips-overview-of-fips-140-2.html 
keywords: fips 120-2, cryptographic module, security level, 
summary: FIPS 140-2 指定了在安全系统中使用的加密模块的安全要求，用于保护计算机和电信系统中的敏感信息。 
---
= FIPS 140-2 概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-cybersecurity-threats-in-healthcare.html["上一篇：医疗保健领域的网络安全威胁。"]

https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf["FIPS 140-2"^] 指定在保护计算机和电信系统中敏感信息的安全系统中使用的加密模块的安全要求。加密模块应为一组硬件，软件，固件或两者的组合。FIPS 适用场景 加密边界内包含的加密算法，密钥生成和密钥管理器。请务必了解， FIPS 140-2 专门适用于加密模块，而不是产品，架构，数据或生态系统。本文档后面的关键术语中定义的加密模块是实施批准的安全功能的特定组件（无论是硬件，软件和 / 或固件）。此外， FIPS 140-2 还指定了四个级别。经过批准的加密算法适用于所有级别。每个安全级别的关键要素和要求包括：

* * 安全级别 1*
+
** 指定加密模块的基本安全要求（至少需要一个经过批准的算法或安全功能）。
** 除了生产级组件的基本要求之外， 1 级不需要任何指定的物理安全机制。


* * 安全级别 2*
+
** 通过使用不受篡改的解决方案（例如，覆盖层或密封，可拆卸盖板或加密模块的门锁）添加篡改证据要求，增强了物理安全机制。
** 至少需要基于角色的访问控制（ Role-Based Access Control ， RBAC ），在此控制中，加密模块对操作员或管理员的授权进行身份验证，以承担特定角色并执行一组相应的功能。


* * 安全级别 3*
+
** 基于 2 级的防篡改要求构建，并尝试防止进一步访问加密模块中的关键安全参数（ CSP ）。
** 第 3 级所需的物理安全机制旨在检测和响应物理访问尝试或对加密模块的任何使用或修改的可能性较高。示例可能包括：打开加密模块上的可拆卸盖时，强磁盘机箱，防拆检测以及将所有纯文本 CSP 置零的响应电路。
** 需要基于身份的身份验证机制来增强级别 2 中指定的 RBAC 机制的安全性。加密模块对操作员身份进行身份验证，并验证操作员是否有权使用某个角色并执行该角色的功能。


* * 安全级别 4*
+
** FIPS 140-2 中最高级别的安全性。
** 在物理上不受保护的环境中执行操作的最有用级别。
** 在这一级别，物理安全机制旨在为加密模块提供全面保护，并负责检测和响应任何未经授权的物理访问尝试。
** 加密模块的渗透或暴露应具有很高的检测概率，并导致所有不安全或纯文本 CSP 立即置零。




link:flexpod-fips-control-plane-versus-data-plane.html["下一步：控制平面与数据平面。"]
