---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_design.html 
keywords: architecture, storage, layout, aggregates, database, disk, type, control, failover, hardware, aff 
summary: 适用于 MEDITECH 的 FlexPod 架构基于 MEDITECH ， Cisco 和 NetApp 的指导以及合作伙伴与各种规模的 MEDITECH 客户合作的经验。该架构具有适应性，并会根据您的数据中心战略，组织规模以及您的系统是集中式系统，分布式系统还是多租户系统，应用 MEDITECH 的最佳实践。 
---
= 设计
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


适用于 MEDITECH 的 FlexPod 架构基于 MEDITECH ， Cisco 和 NetApp 的指导以及合作伙伴与各种规模的 MEDITECH 客户合作的经验。该架构具有适应性，并会根据您的数据中心战略，组织规模以及您的系统是集中式系统，分布式系统还是多租户系统，应用 MEDITECH 的最佳实践。

正确的存储架构可通过总 IOPS 大小来确定。性能本身并不是唯一的因素，您可能会根据其他客户需求决定使用更大的节点数。使用 NetApp 存储的优势在于，您可以根据需求的变化轻松无中断地扩展集群。您也可以从集群中无中断删除节点，以重新利用设备或在设备更新期间使用。

以下是 NetApp ONTAP 存储架构的一些优势：

* * 轻松，无中断地纵向扩展和横向扩展。 * 您可以使用 ONTAP 无中断操作升级，添加或删除磁盘和节点。您可以从四个节点开始，然后移至六个节点或无中断升级到更大的控制器。
* * 存储效率。 * 利用重复数据删除， NetApp FlexClone ，实时压缩，实时数据缩减，精简复制， 精简配置和聚合重复数据删除。通过 FlexClone 功能，您几乎可以即时创建克隆，以支持备份和测试环境更新。只有在进行更改后，这些克隆才会占用更多存储。
* * 灾难恢复卷影数据库服务器。 * 灾难恢复卷影数据库服务器是业务连续性策略的一部分（用于支持存储只读功能，并可能配置为存储读 / 写实例）。因此，第三个存储系统的放置和规模估算通常与生产数据库存储系统中的放置和规模估算相同。
* * 数据库一致性（需要考虑一些因素）。 * 如果您使用 NetApp SnapMirror 备份副本来保持业务连续性，请参见 http://media.netapp.com/documents/tr-3446.pdf["TR-3446 ：《 SnapMirror 异步概述和最佳实践指南》"^]。




== 存储布局



=== 用于 MEDITECH 主机的专用聚合

要满足 MEDITECH 的高性能和高可用性要求，第一步是为 MEDITECH 环境正确设计存储布局，以便将 MEDITECH 主机生产工作负载隔离到专用的高性能存储上。

应在每个存储控制器上配置一个专用聚合，用于存储 MEDITECH 主机的程序，词典和数据文件。为了消除其他工作负载使用相同磁盘并影响性能的可能性，不会从这些聚合配置任何其他存储。


NOTE: 为其他 MEDITECH 服务器配置的存储不应放置在 MEDITECH 主机所使用的 LUN 的专用聚合上。您应将其他 MEDITECH 服务器的存储放置在一个单独的聚合上。有关其他 MEDITECH 服务器的存储要求，请参见《硬件配置建议》（针对新部署）和《硬件评估任务》（针对现有部署）文档。您可以通过 MEDITECH 系统集成商或您的 MEDITECH 技术客户经理（ Technical Account Manager ， TAM ）从 MEDITECH 获取这些文档。NetApp 解决方案工程师可以咨询 NetApp MEDITECH 独立软件供应商（ ISV ）团队，以便正确，完整地配置 NetApp 存储规模估算。



=== 将 MEDITECH 主机工作负载均匀分布在所有存储控制器上

NetApp FAS 和 AFF 系统部署为一个或多个高可用性对。NetApp 建议您在每个存储控制器之间均匀分布 MEDITECH expanse 和 6.x 工作负载，以便在每个存储控制器上应用计算，网络和缓存资源。

请按照以下准则在每个存储控制器之间均匀分布 MEDITECH 工作负载：

* 如果您知道每个 MEDITECH 主机的 IOPS ，则可以通过确认每个控制器从 MEDITECH 主机提供的 IOPS 数量相似，在所有存储控制器之间均匀分布 MEDITECH expanse 和 6.x 工作负载。
* 如果您不知道每个 MEDITECH 主机的 IOPS ，则仍然可以在所有存储控制器之间均匀分布 MEDITECH expanse 和 6.x 工作负载。要完成此任务，请确认 MEDITECH 主机的聚合容量均匀分布在所有存储控制器上。这样，专用于 MEDITECH 主机的所有数据聚合中的磁盘数量都是相同的。
* 使用相似的磁盘类型和相同的 RAID 组为两个控制器创建存储聚合，以便平均分布工作负载。在创建存储聚合之前，请联系 NetApp 认证集成商。



NOTE: 据 MEDITECH 报告， MEDITECH 系统中的两个主机生成的 IOPS 高于其余主机。这两个主机的 LUN 应放置在不同的存储控制器上。在部署系统之前，您应在 MEDITECH 团队的协助下确定这两台主机。



== 存储放置



=== MEDITECH 主机的数据库存储

MEDITECH 主机的数据库存储将作为 NetApp FAS 或 AFF 系统中的块设备（即 LUN ）提供。LUN 通常作为 E 驱动器挂载到 Windows 操作系统。



=== 其他存储

MEDITECH 主机操作系统和数据库应用程序通常会在存储上生成大量 IOPS 。如果需要， MEDITECH 主机 VM 及其 VMDK 文件的存储配置会被视为独立于满足 MEDITECH 性能阈值所需的存储。

为其他 MEDITECH 服务器配置的存储不应放置在 MEDITECH 主机使用的 LUN 的专用聚合上。将其他 MEDITECH 服务器的存储置于单独的聚合上。



== 存储控制器配置



=== 高可用性

要缓解控制器故障的影响并实现存储系统无中断升级，您应在高可用性模式下为存储系统配置高可用性对中的控制器。

在高可用性控制器对配置中，磁盘架应通过多条路径连接到控制器。此连接可防止单路径故障，从而提高存储故障恢复能力，并可在发生控制器故障转移时提高性能一致性。



=== 存储控制器故障转移期间的存储性能

对于在高可用性对中配置了控制器的存储系统，如果发生控制器故障的可能性不大，则配对控制器将接管发生故障的控制器的存储资源和工作负载。请务必咨询客户，以确定发生控制器故障时必须满足的性能要求，并相应地调整系统大小。



=== 硬件辅助接管

NetApp 建议您在两个存储控制器上启用硬件辅助接管功能。

硬件辅助接管旨在最大程度地缩短存储控制器故障转移时间。它使一个控制器的远程 LAN 模块或服务处理器模块能够以比检测信号超时触发器更快的速度向其配对节点通知控制器故障，从而缩短故障转移所需的时间。默认情况下，高可用性配置中的存储控制器会启用硬件辅助接管功能。

有关硬件辅助接管的详细信息，请参见 http://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 文档中心"^]。



=== Disk type

为了满足 MEDITECH 工作负载的低读取延迟要求， NetApp 建议您对专用于 MEDITECH 主机的 AFF 系统上的聚合使用高性能 SSD 。



=== NetApp AFF

NetApp 提供高性能 AFF 阵列，以满足需要高吞吐量，具有随机数据访问模式和低延迟要求的 MEDITECH 工作负载的需求。对于 MEDITECH 工作负载，与基于 HDD 的系统相比， AFF 阵列具有性能优势。闪存技术与企业数据管理相结合，可在三个主要方面提供优势：性能，可用性和存储效率。



=== NetApp 支持工具和服务

NetApp 提供了一整套支持工具和服务。应在 NetApp AFF/FAS 系统上启用和配置 NetApp AutoSupport 工具，以便在发生硬件故障或系统配置不当时回电。致电主页可提醒 NetApp 支持团队及时修复任何问题。NetApp Active IQ 是一款基于 Web 的应用程序，它基于您的 NetApp 系统中的 AutoSupport 信息，可提供预测性和主动式洞察力，帮助提高可用性，效率和性能。
