---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-sizing_meditech_workload_overview.html 
keywords: meditech, workload, backup, cisco, ucs, reference, architecture, platforms 
summary: 本节介绍在 MEDITECH 环境中可能会发现的计算和存储工作负载类型。 
---
= Meditech 工作负载概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本节介绍在 MEDITECH 环境中可能会发现的计算和存储工作负载类型。



== Meditech 和备份工作负载

在为 MEDITECH 环境估算 NetApp 存储系统的规模时，您必须同时考虑 MEDITECH 生产工作负载和备份工作负载。

|===
| MEDITECH 主机 


| MEDITECH 主机是数据库服务器。此主机也称为 MEDITECH 文件服务器（对于 expanse ， 6.x 或 C/S 5.x 平台）或魔力机器（对于魔力平台）。本文档使用术语 MEDITECH 主机来指代 MEDITECH 文件服务器和魔力机器。 
|===
以下各节将介绍这两个工作负载的 I/O 特征和性能要求。



== Meditech 工作负载

在 MEDITECH 环境中，运行 MEDITECH 软件的多个服务器作为一个称为 MEDITECH 系统的集成系统执行各种任务。有关 MEDITECH 系统的详细信息，请参见 MEDITECH 文档：

* 对于生产型 MEDITECH 环境，请参阅相应的 MEDITECH 文档，以确定在调整 NetApp 存储系统规模时必须包含的 MEDITECH 主机数量和存储容量。
* 对于新的 MEDITECH 环境，请参见硬件配置提案文档。对于现有的 MEDITECH 环境，请参阅硬件评估任务文档。硬件评估任务与 MEDITECH 服务单关联。客户可以向 MEDITECH 申请上述任一文档。


您可以通过添加主机来扩展 MEDITECH 系统，以提高容量和性能。每个主机都需要存储容量来存储其数据库和应用程序文件。每个 MEDITECH 主机可用的存储还必须支持该主机生成的 I/O 。在 MEDITECH 环境中，每个主机都有一个 LUN ，以满足该主机的数据库和应用程序存储要求。您部署的 MEDITECH 类别类型和平台类型决定了每个 MEDITECH 主机的工作负载特征，因此也决定了整个系统的工作负载特征。



=== MEDITECH 类别

Meditech 会将部署规模与 1 到 6 之间的类别编号关联起来。类别 1 表示最小的 MEDITECH 部署；类别 6 表示最大的部署。与每个类别关联的 MEDITECH 应用程序规范示例包括以下指标：

* 医院床位数
* 每年住院患者数
* 每年门诊患者
* 每年的紧急房间访问量
* 每年的考试
* 每天为患者开处方
* 每天提供门诊处方


有关 MEDITECH 类别的详细信息，请参见 MEDITECH 类别参考表。您可以通过客户或通过 MEDITECH 系统安装程序从 MEDITECH 获取此表。



=== Meditech 平台

Meditech 有四个平台：

* 贵
* Meditech 6.x
* 客户端 / 服务器 5.x （ C/S 5.x ）
* 魔力


对于 MEDITECH expanse ， 6.x 和 C/S 5.x 平台，每个主机的 I/O 特征均定义为 100% 随机，请求大小为 4 ， 000 。对于 MEDITECH 魔力平台，每台主机的 I/O 特征均定义为 100% 随机，请求大小为 8 ， 000 或 16 ， 000 。据 MEDITECH 报告，典型的魔力生产部署的请求大小为 8 ， 000 或 16 ， 000 。

读取和写入比率因部署的平台而异。Meditech 会估算读写的平均混合比例，然后将其表示为百分比。Meditech 还会估算特定 MEDITECH 平台上的每个 MEDITECH 主机所需的平均持续 IOPS 值。下表总结了 MEDITECH 提供的平台专用 I/O 特征。

|===
| MEDITECH 类别 | Meditech 平台 | 平均随机读取 % | 平均随机写入 % | 每个 MEDITECH 主机的平均持续 IOPS 


| 1. | expanse ， 6.x | 20 | 80 | 750 


.4+| 2-6 | 贵 | 20 | 80 | 750 


| 6.x | 20 | 80 | 750 


| C/S 5.x | 40 | 60 | 600 


| 魔力 | 90 | 10 | 400 
|===
在 MEDITECH 系统中，每个主机的平均 IOPS 级别必须等于上表中定义的 IOPS 值。要根据每个平台确定正确的存储规模估算，请在中所述的规模估算方法中使用上表中指定的 IOPS 值 link:ehr-meditech-sizing_technical_specifications_for_small,_medium_and_large_architectures.html["小型，中型和大型架构的技术规格"] 部分。

Meditech 要求每台主机的平均随机写入延迟保持在 1 毫秒以下。但是，在备份和重新分配作业期间，写入延迟临时增加到 2 毫秒是可以接受的。Meditech 还要求 1 类主机的平均随机读取延迟低于 7 毫秒， 2 类主机的平均随机读取延迟低于 5 毫秒。无论使用哪种 MEDITECH 平台，这些延迟要求都适用于每个主机。

下表总结了在为 MEDITECH 工作负载估算 NetApp 存储规模时必须考虑的 I/O 特征。

|===
| 参数 | MEDITECH 类别 | 贵 | Meditech 6.x | C/S 5.x | 魔力 


| 请求大小 .2+| 1 至 6 | 4k | 4k | 4k | 8 K 或 16 K 


| 随机 / 顺序 | 100% 随机 | 100% 随机 | 100% 随机 | 100% 随机 


.2+| 平均持续 IOPS | 1. | 750 | 750 | 不适用 | 不适用 


| 2-6 | 750 | 750 | 600 | 400 


| 读 / 写比率 .2+| 1 至 6 | 20% 读取， 80% 写入 | 20% 读取， 80% 写入 | 读取率为 40% ，写入率为 60% | 读取率为 90% ，写入率为 10% 


| 写入延迟 | 小于 1 毫秒 | 小于 1 毫秒 | 小于 1 毫秒 | 小于 1 毫秒 


| 临时峰值写入延迟 | 1 至 6 | 小于 2 毫秒 | 小于 2 毫秒 | 小于 2 毫秒 | 小于 2 毫秒 


.2+| 读取延迟 | 1. | < 7 毫秒 | < 7 毫秒 | 不适用 | 不适用 


| 2-6 | 小于 5 毫秒 | 小于 5 毫秒 | 小于 5 毫秒 | 小于 5 毫秒 
|===

NOTE: 3 到 6 类的 Meditech 主机与 2 类具有相同的 I/O 特征。对于 MEDITECH 类别 2 到 6 ，在每个类别中部署的主机数量会有所不同。

NetApp 存储系统的大小应满足前面几节所述的性能要求。除了 MEDITECH 生产工作负载之外， NetApp 存储系统还必须能够在备份操作期间保持这些 MEDITECH 性能目标，如下一节所述。



== 备份工作负载问题描述

经过 Meditech 认证的备份软件可备份由 MEDITECH 系统中的每个 MEDITECH 主机使用的 LUN 。要使备份处于应用程序一致的状态，备份软件将暂停 MEDITECH 系统并暂停对磁盘的 I/O 请求。在系统处于静默状态时，备份软件会向 NetApp 存储系统发出一条命令，为包含 LUN 的卷创建 NetApp Snapshot 副本。备份软件稍后会使 MEDITECH 系统退出静默状态，从而可以继续向数据库发出生产 I/O 请求。该软件将基于 Snapshot 副本创建 NetApp FlexClone 卷。此卷由备份源使用，而生产 I/O 请求则继续在托管 LUN 的父卷上发出。

备份软件生成的工作负载来自对 FlexClone 卷中 LUN 的顺序读取。此工作负载是指请求大小为 64 ， 000 的 100% 顺序读取工作负载。对于 MEDITECH 生产工作负载，性能标准是保持所需的 IOPS 以及相关的读 / 写延迟级别。但是，对于备份工作负载，需要注意备份操作期间生成的整体数据吞吐量（ MBps ）。Meditech LUN 备份需要在八小时的备份时间内完成，但 NetApp 建议在六小时或更短的时间内完成所有 MEDITECH LUN 的备份。如果要在不到六小时的时间内完成备份，则可以减少 MEDITECH 工作负载计划外增加， NetApp ONTAP 后台操作或数据随时间增长等事件的影响。任何此类事件都可能会导致备份时间过长。无论存储的应用程序数据量如何，备份软件都会为每个 MEDITECH 主机对整个 LUN 执行完整的块级备份。

根据其他相关因素，计算完成此窗口中的备份所需的顺序读取吞吐量：

* 所需的备份持续时间
* LUN 的数量
* 要备份的每个 LUN 的大小


例如，在一个 50 主机的 MEDITECH 环境中，每个主机的 LUN 大小为 200 GB ，在此环境中，要备份的 LUN 总容量为 10 TB 。

要在八小时内备份 10 TB 的数据，需要以下吞吐量：

* = （ 10 x 10^6 ） MB （ 8 x 3 ， 600 ） s
* = 347.2 MBps


但是，为了考虑计划外事件，我们会选择一个 5.5 小时的保守备份窗口，以提供超过建议的 6 小时的余量。

要在八小时内备份 10 TB 的数据，需要以下吞吐量：

* = （ 10 x 10^6 ） MB （ 5.5 x 3 ， 600 ） s
* = 500 Mbps


以 500 Mbps 的吞吐量速率，备份可以在 5.5 小时的时间范围内完成，并且可以在 8 小时的备份要求范围内轻松完成。

下表总结了在估算存储系统规模时要使用的备份工作负载的 I/O 特征。

|===
| 参数 | 所有平台 


| 请求大小 | 64K 


| 随机 / 顺序 | 100% 顺序 


| 读 / 写比率 | 100% 读取 


| 平均吞吐量 | 取决于 MEDITECH 主机的数量和每个 LUN 的大小：备份必须在 8 小时内完成。 


| 所需的备份持续时间 | 8 小时 
|===


== 适用于 MEDITECH 的 Cisco UCS 参考架构

基于 FlexPod 的 MEDITECH 的架构基于 MEDITECH ， Cisco 和 NetApp 的指导以及合作伙伴在与各种规模的 MEDITECH 客户合作方面的经验。该架构具有适应性，并会根据客户的数据中心战略应用 MEDITECH 的最佳实践：无论是小型还是大型，集中式，分布式还是多租户。

在部署 MEDITECH 时， Cisco 设计的 Cisco UCS 参考架构直接符合 MEDITECH 的最佳实践。Cisco UCS 提供紧密集成的解决方案，可提供高性能，高可用性，可靠性和可扩展性，支持医生诊疗以及配备数千张床位的医院系统。
