---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: 经过Cisco验证的设计包括设计、测试和记录的系统和解决方案、旨在帮助和改进客户部署。 
---
= FlexPod 数据中心与基于 Cisco UCS 和 NetApp AFF A 系列的 Oracle RAC 数据库
:allow-uri-read: 


Cisco Hardakkumar Vyas公司Tushar Patel

经过Cisco验证的设计包括设计、测试和记录的系统和解决方案、旨在帮助和改进客户部署。这些设计将广泛的技术和产品整合到一个解决方案组合中、这些解决方案是为满足客户的业务需求而开发的。Cisco和NetApp合作推出了FlexPod 、它为各种工作负载奠定了基础、并可根据客户需求进行高效的架构设计。FlexPod 解决方案 是一种经验证的方法、用于将Cisco和NetApp技术部署为共享云基础架构。

采用NetApp全闪存AFF 系统的FlexPod 数据中心是一个融合基础架构平台、它将Cisco和NetApp的同类最佳技术整合到一个功能强大的企业级应用程序融合平台中。Cisco和NetApp与Oracle密切合作、为当今企业所需的最苛刻的事务处理和响应时间敏感型数据库提供支持。

此Cisco验证设计(Cisco Validated Design、CVD)介绍了使用FlexPod UCS和NetApp全闪存AFF 存储部署高可用性Oracle RAC数据库环境的参考数据中心架构。本文档显示了所涉及组件的硬件和软件配置以及各种测试的结果。此外、本文档还提供了使用Cisco UCS计算服务器、Cisco互联阵列交换机、Cisco MDS交换机、Cisco Nexus交换机、NetApp AFF 存储和Oracle RAC数据库的实施和最佳实践指导。

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["FlexPod 数据中心与基于 Cisco UCS 和 NetApp AFF A 系列的 Oracle RAC 数据库"^]
