---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: 检查您是否满足 NetApp ONTAP 存储与 Cisco Intersight 集成的硬件，软件和许可要求。 
---
= 要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
验证您是否满足NetApp ONTAP存储与Cisco Intersight集成的硬件、软件和许可要求。



== 硬件和软件要求

这些是实施解决方案所需的最低硬件和软件组件。在任何特定解决方案实施中使用的组件可能会因客户要求而异。

|===
| 组件 | 需求详细信息 


| NetApp ONTAP | ONTAP 9.7P1 及更高版本 


| NetApp Active IQ Unified Manager | 需要最新版本的NetApp Active IQ Unified Manager (当前为9.14RC1) 


| NetApp 存储阵列 | ONTAP 9.7P1及更高版本支持所有ONTAP ASA、AFF和FAS存储阵列 


| 虚拟化虚拟机管理程序 | vSphere 7.0及更高版本 
|===

NOTE: 请参见 https://intersight.com/help/saas/supported_systems["Cisco Intersight支持的系统"^] 以满足 Cisco UCS 计算组件和 UCSM 版本的最低要求。



== Cisco Intersight 许可要求

思科Intersight提供基础架构服务和Cloud Orchestrator服务等服务、用于管理、自动化和优化物理存储(NetApp存储)。您可以使用这些服务来管理Cisco UCS服务器和Cisco HyperFlex系统。基础架构服务和Cloud Orchestrator服务采用基于订阅的许可模式、并具有多个层。您可以为选定订阅期限选择所需的Cisco UCS Server卷层。

.许可模式
Cisco Intersight基础架构服务许可模式已得到简化，现在提供以下两层：

* *Cisco Intersight Infrastructure Services Essentials *- Essentials许可证层提供服务器管理，包括全局运行状况监控功能、清单、通过Cisco TAC-集成提供主动式支持、多因素身份验证，以及提供SDK和API访问。
* *Cisco Intersight基础架构服务优势*-优势许可证层提供高级服务器管理，具有扩展的可见性、生态系统集成、Cisco和第三方硬件和软件的自动化以及多域解决方案。


有关各个许可层所涵盖功能的详细信息，请访问 https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["基础架构服务许可证"^]。
